# Generated by Django 5.1.6 on 2025-03-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='author',
        ),
        migrations.AddField(
            model_name='photo',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Публикация'),
        ),
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='photo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['-created_at'], name='board_photo_created_7b79de_idx'),
        ),
    ]
