# Generated by Django 5.1.6 on 2025-04-25 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_photo_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='husband',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Доска для постов', 'verbose_name_plural': 'Доска для постов'},
        ),
        migrations.AlterModelOptions(
            name='tagpost',
            options={'verbose_name': 'Теги', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание поста'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='board.tagpost', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='tagpost',
            name='tag',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название тэга'),
        ),
        migrations.CreateModel(
            name='PhotoStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='board.photo')),
            ],
        ),
        migrations.DeleteModel(
            name='Husband',
        ),
        migrations.DeleteModel(
            name='Women',
        ),
    ]
