# Generated by Django 5.1.6 on 2025-04-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_remove_women_husband_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photostats',
            options={'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
    ]
