# Generated by Django 5.1.6 on 2025-04-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_photostats_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='Слаг'),
        ),
    ]
