# Generated by Django 5.1.6 on 2025-06-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_photo_author_photo_dislikes_photo_likes_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.DeleteModel(
            name='PhotoStats',
        ),
    ]
